@startuml
'https://plantuml.com/use-case-diagram

User ---> (Create User)
User ---> (Login)
(Create User) ---> (Casino main)
(Login) ---> (Casino main)
(Casino main) ---> (Black Jack)
(Casino main) ---> (Roulette)



@enduml